# Generated by Django 5.1.11 on 2025-07-22 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0002_alter_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='features',
            field=models.TextField(blank=True, help_text='Ingrese las características separadas por comas', null=True, verbose_name='Características'),
        ),
    ]
